### ISSUE TITLE
Error in Python Runner - Ubuntu

### ISSUE THREAD

**Issue by lucasfreitas1988** [MichaelAquilina/python-tools#169]
Hello, I downloaded the atom and use ubuntu 16.04. I can't run python programs, error appears:
Unable to find command: python
Are you sure PATH is configured correctly?
ENV PATH: :/home/lucas/bin:/home/lucas/.local/bin:/home/lucas/bin:/home/lucas/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

Error: spawn python ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

I am unsure what to do as I only found bad tutorials on the internet. I would like a step by step solution... Thanks!!

**Comment by 9994444ggg** [comment]
I dont know .The utils you have Download was from me ? I Think i cant help you .   Sorry !!!!

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: lucasfreitas1988<mailto:notifications@github.com>
Gesendet: Freitag, 20. Dezember 2019 04:26
An: MichaelAquilina/python-tools<mailto:python-tools@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Betreff: [MichaelAquilina/python-tools] Error in Python Runner - Ubuntu (#169)


Hello, I downloaded the atom and use ubuntu 16.04. I can't run python programs, error appears:
Unable to find command: python
Are you sure PATH is configured correctly?
ENV PATH: :/home/lucas/bin:/home/lucas/.local/bin:/home/lucas/bin:/home/lucas/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

Error: spawn python ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
at onErrorNT (internal/child_process.js:407:16)
at process._tickCallback (internal/process/next_tick.js:63:19)

I am unsure what to do as I only found bad tutorials on the internet. I would like a step by step solution... Thanks!!
