### ISSUE TITLE
python tools failure

### ISSUE THREAD

**Issue by sharonlaker** [MichaelAquilina/python-tools#208]
i set the path in the package setting but still my python tools aren't working. its giving me this error before please help

Unable to find command: python
Are you sure PATH is configured correctly?

ENV PATH: /home/sharon/.local/bin:/home/sharon/.local/bin:/home/sharon/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

Error: spawn python ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

**Comment by 9994444ggg** [comment]
No sorry you have this Pyton Tolls from me.

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: sharonlaker<mailto:notifications@github.com>
Gesendet: Samstag, 11. Juli 2020 08:48 Uhr
An: MichaelAquilina/python-tools<mailto:python-tools@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Betreff: [MichaelAquilina/python-tools] python tools failure (#208)


i set the path in the package setting but still my python tools aren't working. its giving me this error before please help

Unable to find command: python
Are you sure PATH is configured correctly?

ENV PATH: /home/sharon/.local/bin:/home/sharon/.local/bin:/home/sharon/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

Error: spawn python ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
at onErrorNT (internal/child_process.js:429:16)
at processTicksAndRejections (internal/process/task_queues.js:81:17)
